### ISSUE TITLE
Building the Inventory : ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by ksingh7** [ceph/cephmetrics-osp#3]
While trying to build inventory, i am getting the following error. Is there anything wrong with this command ?

```
$ ./convert_inventory.py -a cephmetrics.conf ooo-inventory.yaml > inventory.yaml
Traceback (most recent call last):
  File "./convert_inventory.py", line 189, in <module>
    new_host_conf = load_file(args.add_host)
  File "./convert_inventory.py", line 55, in load_file
    key, value = line.split('=', 1)
ValueError: need more than 1 value to unpack
$
```

**Comment by fultonj** [comment]
Please provide the generated inventory.yaml from before and after this change

**Comment by zmc** [comment]
What file is being read that causes you to think it's a kernel issue?

In addition to the inventory, please attach the conf file you passed to it.

**Comment by zmc** [comment]
The issue was the `.conf` file having blank lines :-/
